### ISSUE TITLE
Make force_plurals Sync + Send?

### ISSUE THREAD

**Issue by mjanda** [justinas/gettext#1]
Hello, I'm trying to use this package in multi-threaded environment and it complaints about force_plurals.

I was able to make it compile by changing signature to `Fn(u64) -> usize + Send + Sync + 'static` inside gettext package itself, but I'm not sure if that's the right way (still in that borrow checker fighting phase). Is this the right way to do this or am I missing something and it's possible without modifying gettext source itself?

Thank you

**Comment by justinas** [comment]
@mjanda I somehow missed this issue completely...

There is some work in #2 happening right now that touches the plural resolver. Adding Send and Sync bounds should not be a problem, but as a further step `force_plurals` might be changed to accept `fn` instead of `Fn`, at least until cloning of closures is stabilized.

**Comment by justinas** [comment]
Version 0.3.0 has been released today. Among other things, the function resolver has been changed to use `fn` which are Send and Sync by default.

There is now also [a check](https://github.com/justinas/gettext/blob/5e1c5c9ffacdfbe744e17ba5273423b7d286d9dc/src/lib.rs#L201) to ensure Catalog implements Send and Sync.
